// Создано scripts/sync-countries.py — руками не править.
// Источник: CLDR 48.2.2, cldr-localenames-full/main/{ru,en}/territories.json.

/// (код, русский, английский), по возрастанию кода.
pub static COUNTRIES: &[(&str, &str, &str)] = &[
    ("AC", "о-в Вознесения", "Ascension Island"),
    ("AD", "Андорра", "Andorra"),
    ("AE", "ОАЭ", "United Arab Emirates"),
    ("AF", "Афганистан", "Afghanistan"),
    ("AG", "Антигуа и Барбуда", "Antigua & Barbuda"),
    ("AI", "Ангилья", "Anguilla"),
    ("AL", "Албания", "Albania"),
    ("AM", "Армения", "Armenia"),
    ("AO", "Ангола", "Angola"),
    ("AQ", "Антарктида", "Antarctica"),
    ("AR", "Аргентина", "Argentina"),
    ("AS", "Американское Самоа", "American Samoa"),
    ("AT", "Австрия", "Austria"),
    ("AU", "Австралия", "Australia"),
    ("AW", "Аруба", "Aruba"),
    ("AX", "Аландские о-ва", "Åland Islands"),
    ("AZ", "Азербайджан", "Azerbaijan"),
    ("BA", "Босния и Герцеговина", "Bosnia & Herzegovina"),
    ("BB", "Барбадос", "Barbados"),
    ("BD", "Бангладеш", "Bangladesh"),
    ("BE", "Бельгия", "Belgium"),
    ("BF", "Буркина-Фасо", "Burkina Faso"),
    ("BG", "Болгария", "Bulgaria"),
    ("BH", "Бахрейн", "Bahrain"),
    ("BI", "Бурунди", "Burundi"),
    ("BJ", "Бенин", "Benin"),
    ("BL", "Сен-Бартелеми", "St. Barthélemy"),
    ("BM", "Бермудские о-ва", "Bermuda"),
    ("BN", "Бруней", "Brunei"),
    ("BO", "Боливия", "Bolivia"),
    ("BQ", "Бонэйр, Синт-Эстатиус и Саба", "Caribbean Netherlands"),
    ("BR", "Бразилия", "Brazil"),
    ("BS", "Багамы", "Bahamas"),
    ("BT", "Бутан", "Bhutan"),
    ("BV", "о-в Буве", "Bouvet Island"),
    ("BW", "Ботсвана", "Botswana"),
    ("BY", "Беларусь", "Belarus"),
    ("BZ", "Белиз", "Belize"),
    ("CA", "Канада", "Canada"),
    ("CC", "Кокосовые о-ва", "Cocos (Keeling) Islands"),
    ("CD", "Конго - Киншаса", "Congo - Kinshasa"),
    ("CF", "Центрально-Африканская Республика", "Central African Republic"),
    ("CG", "Конго - Браззавиль", "Congo - Brazzaville"),
    ("CH", "Швейцария", "Switzerland"),
    ("CI", "Кот-д’Ивуар", "Côte d’Ivoire"),
    ("CK", "о-ва Кука", "Cook Islands"),
    ("CL", "Чили", "Chile"),
    ("CM", "Камерун", "Cameroon"),
    ("CN", "Китай", "China"),
    ("CO", "Колумбия", "Colombia"),
    ("CP", "о-в Клиппертон", "Clipperton Island"),
    ("CQ", "Сарк", "Sark"),
    ("CR", "Коста-Рика", "Costa Rica"),
    ("CU", "Куба", "Cuba"),
    ("CV", "Кабо-Верде", "Cape Verde"),
    ("CW", "Кюрасао", "Curaçao"),
    ("CX", "о-в Рождества", "Christmas Island"),
    ("CY", "Кипр", "Cyprus"),
    ("CZ", "Чехия", "Czechia"),
    ("DE", "Германия", "Germany"),
    ("DG", "Диего-Гарсия", "Diego Garcia"),
    ("DJ", "Джибути", "Djibouti"),
    ("DK", "Дания", "Denmark"),
    ("DM", "Доминика", "Dominica"),
    ("DO", "Доминиканская Республика", "Dominican Republic"),
    ("DZ", "Алжир", "Algeria"),
    ("EA", "Сеута и Мелилья", "Ceuta & Melilla"),
    ("EC", "Эквадор", "Ecuador"),
    ("EE", "Эстония", "Estonia"),
    ("EG", "Египет", "Egypt"),
    ("EH", "Западная Сахара", "Western Sahara"),
    ("ER", "Эритрея", "Eritrea"),
    ("ES", "Испания", "Spain"),
    ("ET", "Эфиопия", "Ethiopia"),
    ("EU", "Европейский союз", "European Union"),
    ("EZ", "еврозона", "Eurozone"),
    ("FI", "Финляндия", "Finland"),
    ("FJ", "Фиджи", "Fiji"),
    ("FK", "Фолклендские о-ва", "Falkland Islands"),
    ("FM", "Федеративные Штаты Микронезии", "Micronesia"),
    ("FO", "Фарерские о-ва", "Faroe Islands"),
    ("FR", "Франция", "France"),
    ("GA", "Габон", "Gabon"),
    ("GB", "Великобритания", "United Kingdom"),
    ("GD", "Гренада", "Grenada"),
    ("GE", "Грузия", "Georgia"),
    ("GF", "Французская Гвиана", "French Guiana"),
    ("GG", "Гернси", "Guernsey"),
    ("GH", "Гана", "Ghana"),
    ("GI", "Гибралтар", "Gibraltar"),
    ("GL", "Гренландия", "Greenland"),
    ("GM", "Гамбия", "Gambia"),
    ("GN", "Гвинея", "Guinea"),
    ("GP", "Гваделупа", "Guadeloupe"),
    ("GQ", "Экваториальная Гвинея", "Equatorial Guinea"),
    ("GR", "Греция", "Greece"),
    ("GS", "Южная Георгия и Южные Сандвичевы о-ва", "South Georgia & South Sandwich Islands"),
    ("GT", "Гватемала", "Guatemala"),
    ("GU", "Гуам", "Guam"),
    ("GW", "Гвинея-Бисау", "Guinea-Bissau"),
    ("GY", "Гайана", "Guyana"),
    ("HK", "Гонконг (САР)", "Hong Kong SAR China"),
    ("HM", "о-ва Херд и Макдональд", "Heard & McDonald Islands"),
    ("HN", "Гондурас", "Honduras"),
    ("HR", "Хорватия", "Croatia"),
    ("HT", "Гаити", "Haiti"),
    ("HU", "Венгрия", "Hungary"),
    ("IC", "Канарские о-ва", "Canary Islands"),
    ("ID", "Индонезия", "Indonesia"),
    ("IE", "Ирландия", "Ireland"),
    ("IL", "Израиль", "Israel"),
    ("IM", "о-в Мэн", "Isle of Man"),
    ("IN", "Индия", "India"),
    ("IO", "Британская территория в Индийском океане", "British Indian Ocean Territory"),
    ("IQ", "Ирак", "Iraq"),
    ("IR", "Иран", "Iran"),
    ("IS", "Исландия", "Iceland"),
    ("IT", "Италия", "Italy"),
    ("JE", "Джерси", "Jersey"),
    ("JM", "Ямайка", "Jamaica"),
    ("JO", "Иордания", "Jordan"),
    ("JP", "Япония", "Japan"),
    ("KE", "Кения", "Kenya"),
    ("KG", "Киргизия", "Kyrgyzstan"),
    ("KH", "Камбоджа", "Cambodia"),
    ("KI", "Кирибати", "Kiribati"),
    ("KM", "Коморы", "Comoros"),
    ("KN", "Сент-Китс и Невис", "St. Kitts & Nevis"),
    ("KP", "КНДР", "North Korea"),
    ("KR", "Республика Корея", "South Korea"),
    ("KW", "Кувейт", "Kuwait"),
    ("KY", "о-ва Кайман", "Cayman Islands"),
    ("KZ", "Казахстан", "Kazakhstan"),
    ("LA", "Лаос", "Laos"),
    ("LB", "Ливан", "Lebanon"),
    ("LC", "Сент-Люсия", "St. Lucia"),
    ("LI", "Лихтенштейн", "Liechtenstein"),
    ("LK", "Шри-Ланка", "Sri Lanka"),
    ("LR", "Либерия", "Liberia"),
    ("LS", "Лесото", "Lesotho"),
    ("LT", "Литва", "Lithuania"),
    ("LU", "Люксембург", "Luxembourg"),
    ("LV", "Латвия", "Latvia"),
    ("LY", "Ливия", "Libya"),
    ("MA", "Марокко", "Morocco"),
    ("MC", "Монако", "Monaco"),
    ("MD", "Молдова", "Moldova"),
    ("ME", "Черногория", "Montenegro"),
    ("MF", "Сен-Мартен", "St. Martin"),
    ("MG", "Мадагаскар", "Madagascar"),
    ("MH", "Маршалловы о-ва", "Marshall Islands"),
    ("MK", "Северная Македония", "North Macedonia"),
    ("ML", "Мали", "Mali"),
    ("MM", "Мьянма (Бирма)", "Myanmar (Burma)"),
    ("MN", "Монголия", "Mongolia"),
    ("MO", "Макао (САР)", "Macao SAR China"),
    ("MP", "Северные Марианские о-ва", "Northern Mariana Islands"),
    ("MQ", "Мартиника", "Martinique"),
    ("MR", "Мавритания", "Mauritania"),
    ("MS", "Монтсеррат", "Montserrat"),
    ("MT", "Мальта", "Malta"),
    ("MU", "Маврикий", "Mauritius"),
    ("MV", "Мальдивы", "Maldives"),
    ("MW", "Малави", "Malawi"),
    ("MX", "Мексика", "Mexico"),
    ("MY", "Малайзия", "Malaysia"),
    ("MZ", "Мозамбик", "Mozambique"),
    ("NA", "Намибия", "Namibia"),
    ("NC", "Новая Каледония", "New Caledonia"),
    ("NE", "Нигер", "Niger"),
    ("NF", "о-в Норфолк", "Norfolk Island"),
    ("NG", "Нигерия", "Nigeria"),
    ("NI", "Никарагуа", "Nicaragua"),
    ("NL", "Нидерланды", "Netherlands"),
    ("NO", "Норвегия", "Norway"),
    ("NP", "Непал", "Nepal"),
    ("NR", "Науру", "Nauru"),
    ("NU", "Ниуэ", "Niue"),
    ("NZ", "Новая Зеландия", "New Zealand"),
    ("OM", "Оман", "Oman"),
    ("PA", "Панама", "Panama"),
    ("PE", "Перу", "Peru"),
    ("PF", "Французская Полинезия", "French Polynesia"),
    ("PG", "Папуа — Новая Гвинея", "Papua New Guinea"),
    ("PH", "Филиппины", "Philippines"),
    ("PK", "Пакистан", "Pakistan"),
    ("PL", "Польша", "Poland"),
    ("PM", "Сен-Пьер и Микелон", "St. Pierre & Miquelon"),
    ("PN", "о-ва Питкэрн", "Pitcairn Islands"),
    ("PR", "Пуэрто-Рико", "Puerto Rico"),
    ("PS", "Палестинские территории", "Palestinian Territories"),
    ("PT", "Португалия", "Portugal"),
    ("PW", "Палау", "Palau"),
    ("PY", "Парагвай", "Paraguay"),
    ("QA", "Катар", "Qatar"),
    ("QO", "Внешняя Океания", "Outlying Oceania"),
    ("RE", "Реюньон", "Réunion"),
    ("RO", "Румыния", "Romania"),
    ("RS", "Сербия", "Serbia"),
    ("RU", "Россия", "Russia"),
    ("RW", "Руанда", "Rwanda"),
    ("SA", "Саудовская Аравия", "Saudi Arabia"),
    ("SB", "Соломоновы о-ва", "Solomon Islands"),
    ("SC", "Сейшельские о-ва", "Seychelles"),
    ("SD", "Судан", "Sudan"),
    ("SE", "Швеция", "Sweden"),
    ("SG", "Сингапур", "Singapore"),
    ("SH", "о-в Св. Елены", "St. Helena"),
    ("SI", "Словения", "Slovenia"),
    ("SJ", "Шпицберген и Ян-Майен", "Svalbard & Jan Mayen"),
    ("SK", "Словакия", "Slovakia"),
    ("SL", "Сьерра-Леоне", "Sierra Leone"),
    ("SM", "Сан-Марино", "San Marino"),
    ("SN", "Сенегал", "Senegal"),
    ("SO", "Сомали", "Somalia"),
    ("SR", "Суринам", "Suriname"),
    ("SS", "Южный Судан", "South Sudan"),
    ("ST", "Сан-Томе и Принсипи", "São Tomé & Príncipe"),
    ("SV", "Сальвадор", "El Salvador"),
    ("SX", "Синт-Мартен", "Sint Maarten"),
    ("SY", "Сирия", "Syria"),
    ("SZ", "Эсватини", "Eswatini"),
    ("TA", "Тристан-да-Кунья", "Tristan da Cunha"),
    ("TC", "Тёркс и Кайкос", "Turks & Caicos Islands"),
    ("TD", "Чад", "Chad"),
    ("TF", "Французские Южные территории", "French Southern Territories"),
    ("TG", "Того", "Togo"),
    ("TH", "Таиланд", "Thailand"),
    ("TJ", "Таджикистан", "Tajikistan"),
    ("TK", "Токелау", "Tokelau"),
    ("TL", "Восточный Тимор", "Timor-Leste"),
    ("TM", "Туркменистан", "Turkmenistan"),
    ("TN", "Тунис", "Tunisia"),
    ("TO", "Тонга", "Tonga"),
    ("TR", "Турция", "Türkiye"),
    ("TT", "Тринидад и Тобаго", "Trinidad & Tobago"),
    ("TV", "Тувалу", "Tuvalu"),
    ("TW", "Тайвань", "Taiwan"),
    ("TZ", "Танзания", "Tanzania"),
    ("UA", "Украина", "Ukraine"),
    ("UG", "Уганда", "Uganda"),
    ("UM", "Внешние малые о-ва (США)", "U.S. Outlying Islands"),
    ("UN", "Организация Объединенных Наций", "United Nations"),
    ("US", "Соединенные Штаты", "United States"),
    ("UY", "Уругвай", "Uruguay"),
    ("UZ", "Узбекистан", "Uzbekistan"),
    ("VA", "Ватикан", "Vatican City"),
    ("VC", "Сент-Винсент и Гренадины", "St. Vincent & Grenadines"),
    ("VE", "Венесуэла", "Venezuela"),
    ("VG", "Виргинские о-ва (Великобритания)", "British Virgin Islands"),
    ("VI", "Виргинские о-ва (США)", "U.S. Virgin Islands"),
    ("VN", "Вьетнам", "Vietnam"),
    ("VU", "Вануату", "Vanuatu"),
    ("WF", "Уоллис и Футуна", "Wallis & Futuna"),
    ("WS", "Самоа", "Samoa"),
    ("XA", "псевдоакценты", "Pseudo-Accents"),
    ("XB", "псевдо-Bidi", "Pseudo-Bidi"),
    ("XK", "Косово", "Kosovo"),
    ("YE", "Йемен", "Yemen"),
    ("YT", "Майотта", "Mayotte"),
    ("ZA", "Южно-Африканская Республика", "South Africa"),
    ("ZM", "Замбия", "Zambia"),
    ("ZW", "Зимбабве", "Zimbabwe"),
    ("ZZ", "неизвестный регион", "Unknown Region"),
];
