[package]
name = "melogold-gtk"
description = "Melogold для Linux: интерфейс на GTK 4 и libadwaita"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "melogold"
path = "src/main.rs"

[dependencies]
melogold-core = { path = "../melogold-core" }
melogold-innertube = { path = "../melogold-innertube" }
melogold-playback = { path = "../melogold-playback" }
futures-util.workspace = true
gst.workspace = true
hex.workspace = true
reqwest.workspace = true
sha2.workspace = true
zbus.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-channel.workspace = true
gtk.workspace = true
url.workspace = true
adw.workspace = true

[build-dependencies]
glib-build-tools = "0.22"
