// Создано scripts/sync-strings.py — руками не править.
// Источник: melogoldWindows/src/Melogold.App/Strings/*/Resources.resw, коммит b48b8cf.

/// (ключ, русский, английский), по возрастанию ключа.
pub static STRINGS: &[(&str, &str, &str)] = &[
    ("AccessKeySettings", "А", "S"),
    ("AccountAddDevice", "Добавить устройство", "Add a device"),
    ("AccountAuthRequiredText", "Сервер завершил сеанс. Библиотека осталась на устройстве", "The server ended the session. Your library is still on this device"),
    ("AccountAuthRequiredTitle", "Нужно войти снова", "Sign in again"),
    ("AccountDeviceCurrent", "Это устройство", "This device"),
    ("AccountDeviceRevoke", "Отвязать", "Unlink"),
    ("AccountDeviceRevokeText", "На нём выйдет из аккаунта, библиотека на нём останется", "It signs out of the account and keeps its library"),
    ("AccountDeviceRevokeTitleFormat", "Отвязать «{0}»?", "Unlink “{0}”?"),
    ("AccountDeviceSeenFormat", "Был в сети {0}", "Last seen {0}"),
    ("AccountDevicesGroup", "Устройства", "Devices"),
    ("AccountErrorCredentials", "Неверный логин или пароль", "Wrong login or password"),
    ("AccountErrorDeviceLimit", "На аккаунте уже максимум устройств. Отвяжите одно из них на другом устройстве", "The account already has the most devices it can. Unlink one on another device"),
    ("AccountErrorInvalidPassword", "Неверный пароль", "Wrong password"),
    ("AccountErrorLoginFormat", "Логин: 3–32 символа, латиница, цифры, точка, _ и -", "Login: 3–32 characters, Latin letters, digits, dot, _ and -"),
    ("AccountErrorLoginTaken", "Этот логин уже занят", "This login is taken"),
    ("AccountErrorNetwork", "Нет связи с сервером", "Can't reach the server"),
    ("AccountErrorPasswordMismatch", "Пароли не совпадают", "The passwords don't match"),
    ("AccountErrorPasswordNeeded", "Это устройство новое на аккаунте: подтвердите паролем", "This device is new on the account: confirm with the password"),
    ("AccountErrorPasswordShort", "Пароль короче 8 символов", "The password is shorter than 8 characters"),
    ("AccountErrorPasswordWeak", "Пароль слишком простой. Возьмите длиннее или фразу из нескольких слов", "The password is too easy to guess. Make it longer or a phrase of a few words"),
    ("AccountErrorRegistrationClosed", "Регистрация на этом сервере закрыта", "Registration is closed on this server"),
    ("AccountErrorThrottled", "Слишком много попыток. Попробуйте через несколько минут", "Too many attempts. Try again in a few minutes"),
    ("AccountErrorUnknown", "Не получилось. Попробуйте ещё раз", "Something went wrong. Try again"),
    ("AccountLogin", "Логин", "Login"),
    ("AccountLoginHint", "3–32 символа: латиница, цифры, точка, _ и -", "3–32 characters: Latin letters, digits, dot, _ and -"),
    ("AccountNoAccount", "Нет аккаунта? Создать", "No account? Create one"),
    ("AccountOnServerFormat", "Сервер: {0}", "Server: {0}"),
    ("AccountPassword", "Пароль", "Password"),
    ("AccountPasswordConfirm", "Подтвердить", "Confirm"),
    ("AccountPasswordHint", "Не короче 8 символов", "At least 8 characters"),
    ("AccountPasswordRepeat", "Пароль ещё раз", "Password again"),
    ("AccountRecoveryCopied", "Код скопирован", "Code copied"),
    ("AccountRecoveryCopy", "Копировать", "Copy"),
    ("AccountRecoverySaved", "Я сохранил код", "I saved the code"),
    ("AccountRecoveryText", "Если забудете пароль, этот код вернёт доступ к аккаунту. Он показывается один раз: сохраните его в менеджере паролей или запишите", "If you forget the password, this code gets you back into the account. It is shown only once: keep it in a password manager or write it down"),
    ("AccountRecoveryTitle", "Код восстановления", "Recovery code"),
    ("AccountRegister", "Создать аккаунт", "Create account"),
    ("AccountRegisterText", "Нужны только логин и пароль. Почту и телефон сервер не спрашивает", "Only a login and a password. The server never asks for an email or a phone number"),
    ("AccountRegisterTitle", "Новый аккаунт", "New account"),
    ("AccountRevokeOthers", "Выйти на других устройствах", "Sign out on other devices"),
    ("AccountRevokeOthersText", "Все устройства, кроме этого, выйдут из аккаунта", "Every device but this one signs out of the account"),
    ("AccountRevokeOthersTitle", "Выйти на других устройствах?", "Sign out on other devices?"),
    ("AccountRevokedOthersFormat", "Устройств отвязано: {0}", "Devices unlinked: {0}"),
    ("AccountSignIn", "Войти", "Sign in"),
    ("AccountSignInText", "Войдите, чтобы Избранное, плейлисты и сохранённые альбомы были одинаковыми на всех ваших устройствах", "Sign in to have the same Favorites, playlists and saved albums on all your devices"),
    ("AccountSignInTitle", "Вход", "Sign in"),
    ("AccountSignInWithCode", "Войти по коду", "Sign in with a code"),
    ("AccountSignOut", "Выйти", "Sign out"),
    ("AccountSignOutText", "Библиотека останется на этом устройстве, но перестанет синхронизироваться", "The library stays on this device but stops syncing"),
    ("AccountSignOutTitle", "Выйти из аккаунта?", "Sign out of the account?"),
    ("AccountSignedInAsFormat", "Вы вошли как {0}", "Signed in as {0}"),
    ("AccountSyncGroup", "Синхронизация", "Sync"),
    ("AccountSyncNow", "Синхронизировать сейчас", "Sync now"),
    ("AccountSyncWhat", "Избранное, плейлисты, сохранённые альбомы и исполнители", "Favorites, playlists, saved albums and artists"),
    ("AddToPlaylistTitle", "Добавить в плейлист", "Add to playlist"),
    ("AddedToPlaylistFormat", "Добавлено в „{0}“", "Added to “{0}”"),
    ("AddedToQueueFormat", "В конце очереди: {0}", "Added to queue: {0}"),
    ("AddedToQueueTracks_few", "В конце очереди: {0} трека", "Added to queue: {0} tracks"),
    ("AddedToQueueTracks_many", "В конце очереди: {0} треков", "Added to queue: {0} tracks"),
    ("AddedToQueueTracks_one", "В конце очереди: {0} трек", "Added to queue: {0} track"),
    ("AddedToQueueTracks_other", "В конце очереди: {0} трека", "Added to queue: {0} tracks"),
    ("AlbumsEmpty", "Сохранённых альбомов пока нет", "No saved albums yet"),
    ("AlbumsEmptyHint", "Здесь появятся сохранённые альбомы", "Saved albums will appear here"),
    ("Albums_few", "{0} альбома", "{0} albums"),
    ("Albums_many", "{0} альбомов", "{0} albums"),
    ("Albums_one", "{0} альбом", "{0} album"),
    ("Albums_other", "{0} альбома", "{0} albums"),
    ("AllTime", "Всё время", "All time"),
    ("AllTracks", "Все треки", "All tracks"),
    ("AllTracksEmpty", "Здесь будут все треки, которые вы слушали, лайкали или добавляли в плейлисты", "All the tracks you played, liked or added to playlists will be here"),
    ("AppTitleBar.Title", "Melogold", "Melogold"),
    ("ArtistAbout", "Об исполнителе", "About"),
    ("ArtistSubscribersFormat", "Подписчиков: {0}", "Subscribers: {0}"),
    ("ArtistsAndChannels", "Исполнители и каналы", "Artists & channels"),
    ("ArtistsEmpty", "Подписок пока нет", "No subscriptions yet"),
    ("ArtistsEmptyHint", "Здесь появятся исполнители и каналы, на которые вы подписались", "Artists and channels you subscribe to will appear here"),
    ("Artists_few", "{0} исполнителя", "{0} artists"),
    ("Artists_many", "{0} исполнителей", "{0} artists"),
    ("Artists_one", "{0} исполнитель", "{0} artist"),
    ("Artists_other", "{0} исполнителя", "{0} artists"),
    ("Back", "Назад", "Back"),
    ("BackupFailed", "Не удалось сохранить копию", "Could not save the copy"),
    ("BackupFileType", "База данных Melogold", "Melogold database"),
    ("BackupSaved", "Копия сохранена", "Copy saved"),
    ("BlacklistEmpty", "Черный список пуст", "The blacklist is empty"),
    ("CacheUnlimited", "Без ограничений", "Unlimited"),
    ("CacheUsedFormat", "{0} использовано · тексты и подборки, найденные в сети", "{0} used · lyrics and picks found online"),
    ("CacheUsedOfFormat", "Занято {0} из {1}", "{0} of {1} used"),
    ("CacheUsedOfUnlimitedFormat", "Занято {0}", "{0} used"),
    ("CacheUsedPercentFormat", "{0} использовано ({1}%)", "{0} used ({1}%)"),
    ("CacheUsedPlainFormat", "{0} использовано", "{0} used"),
    ("Cancel", "Отмена", "Cancel"),
    ("ChangedInPlaylists_few", "Изменено в {0} плейлистах", "Changed in {0} playlists"),
    ("ChangedInPlaylists_many", "Изменено в {0} плейлистах", "Changed in {0} playlists"),
    ("ChangedInPlaylists_one", "Изменено в {0} плейлисте", "Changed in {0} playlist"),
    ("ChangedInPlaylists_other", "Изменено в {0} плейлиста", "Changed in {0} playlists"),
    ("CheckUpdates", "Проверить обновления", "Check for updates"),
    ("CheckUpdatesButton.Content", "Проверить обновления", "Check for updates"),
    ("ChooseLyricTrack", "Выберите трек с текстом", "Choose a track with lyrics"),
    ("Clear", "Очистить", "Clear"),
    ("ClearCacheButton.Content", "Очистить", "Clear"),
    ("ClearHistory", "Очистить историю…", "Clear history…"),
    ("ClearHistoryEverywherePromptFormat", "Удалить все прослушивания ({0}) на всех устройствах аккаунта? Избранное и плейлисты не изменятся.", "Delete all plays ({0}) on every device of the account? Favorites and playlists stay as they are."),
    ("ClearHistoryPromptFormat", "Удалить все прослушивания ({0})? Избранное и плейлисты не изменятся.", "Delete all plays ({0})? Favorites and playlists stay as they are."),
    ("ClearHistoryText", "Все прослушивания удалятся. Избранное и плейлисты не изменятся", "All plays will be deleted. Favorites and playlists stay as they are"),
    ("ClearHistoryTitle", "Очистить историю?", "Clear history?"),
    ("ClearImagesButton.Content", "Очистить", "Clear"),
    ("ClearSearchesButton.Content", "Очистить", "Clear"),
    ("ClearSongsButton.Content", "Очистить кэш", "Clear cache"),
    ("ClipboardLink", "Ссылка из буфера обмена", "Link from the clipboard"),
    ("Close", "Закрыть", "Close"),
    ("CodeAccountFormat", "Вход в аккаунт {0}", "Signing in to {0}"),
    ("CodeChooseFormat", "Выберите это число на «{0}»", "Choose this number on “{0}”"),
    ("CodeEnterHint", "Введите код, который показывает другое устройство: Аккаунт › Добавить устройство › Показать код для нового устройства", "Enter the code another device shows: Account › Add device › Show a code for a new device"),
    ("CodeEnterOther", "Ввести другой код", "Enter another code"),
    ("CodeErrCancelled", "Вход отменили на другом устройстве", "Sign-in was canceled on the other device"),
    ("CodeErrDenied", "Вход отклонён на другом устройстве", "Sign-in was denied on the other device"),
    ("CodeErrExpiredInvite", "Код устарел. Покажите новый на устройстве, где вы уже вошли", "The code has expired. Show a new one on the device where you're signed in"),
    ("CodeErrExpiredRequest", "Код устарел. Получите новый", "The code has expired. Get a new one"),
    ("CodeErrWrongMode", "Это код нового устройства. Введите его там, где вы уже вошли: Аккаунт › Добавить устройство", "This is a new device's code. Enter it where you're signed in: Account › Add device"),
    ("CodeGetNew", "Получить новый код", "Get a new code"),
    ("CodeGetting", "Получаем код…", "Getting a code…"),
    ("CodeHaveOther", "У меня есть код с другого устройства", "I have a code from another device"),
    ("CodeNumberSpokenFormat", "Число {0}", "Number {0}"),
    ("CodeReconnecting", "Нет связи с сервером. Пробуем снова…", "Can't reach the server. Trying again…"),
    ("CodeShowMine", "Показать мой код", "Show my code"),
    ("CodeSignInText", "На устройстве, где вы уже вошли, откройте Аккаунт › Добавить устройство и введите этот код", "On a device where you're signed in, open Account › Add device and enter this code"),
    ("CodeSignInTitle", "Вход по коду", "Sign in with a code"),
    ("CodeSigningIn", "Входим…", "Signing in…"),
    ("CodeSpokenFormat", "Код для входа: {0}", "Sign-in code: {0}"),
    ("CodeUsePassword", "Войти по паролю", "Sign in with a password"),
    ("CodeValidFormat", "Действует {0}", "Valid for {0}"),
    ("ComingSoon", "Скоро здесь", "Coming soon"),
    ("Days30", "30 дней", "30 days"),
    ("Days7", "7 дней", "7 days"),
    ("DaysAgo_few", "{0} дня назад", "{0} days ago"),
    ("DaysAgo_many", "{0} дней назад", "{0} days ago"),
    ("DaysAgo_one", "{0} день назад", "{0} day ago"),
    ("DaysAgo_other", "{0} дня назад", "{0} days ago"),
    ("DeletePlaylist", "Удалить плейлист", "Delete playlist"),
    ("DescriptionLicense", "Лицензия:", "License:"),
    ("DescriptionSource", "Источник:", "Source:"),
    ("DescriptionWikipedia", "Википедия", "Wikipedia"),
    ("DeviceComputer", "Компьютер", "Computer"),
    ("DeviceHeadset", "Гарнитура", "Headset"),
    ("DeviceOther", "Устройство", "Device"),
    ("DevicePhone", "Телефон", "Phone"),
    ("DeviceTablet", "Планшет", "Tablet"),
    ("DeviceWatch", "Часы", "Watch"),
    ("Diagnostics", "Диагностика", "Diagnostics"),
    ("Done", "Готово", "Done"),
    ("DownloadCompleted", "Скачано", "Downloaded"),
    ("DownloadFailed", "Не удалось скачать", "Couldn't download"),
    ("DownloadQueued", "В очереди на загрузку", "Queued for download"),
    ("DownloadRemoved", "Загрузка удалена", "Download removed"),
    ("DownloadStarting", "Скачивается", "Downloading"),
    ("DownloadWaiting", "Ждёт: YouTube не пускает этот адрес", "Waiting: YouTube is blocking this address"),
    ("DownloadingCountFormat", "Скачивается: {0}", "Downloading: {0}"),
    ("DownloadingFormat", "Скачивается · {0} %", "Downloading · {0}%"),
    ("Downloads", "Скачанное", "Downloads"),
    ("DownloadsCachedCountFormat", "В кэше: {0}", "Cached: {0}"),
    ("DownloadsCachedEmpty", "Здесь будут треки, прослушанные целиком: они играют без сети", "Tracks played to the end will be here: they play offline"),
    ("DownloadsCachedFormat", "В кэше · {0} · {1}", "Cached · {0} · {1}"),
    ("DownloadsCachedNote", "Скачанное — насовсем. «В кэше» играет без сети, пока его не сменят новые треки; ⋯ › Скачать оставит трек насовсем — сразу и без сети.", "Downloads stay for good. Cached tracks play without a network until newer ones replace them; ⋯ › Download keeps a track for good, at once and without a network."),
    ("DownloadsCountFormat", "Скачано: {0} · в кэше: {1}", "Downloaded: {0} · cached: {1}"),
    ("DownloadsDownloadedFormat", "Скачано · {0} · {1}", "Downloaded · {0} · {1}"),
    ("DownloadsEmpty", "Скачайте треки — они будут играть без сети. ⋯ › Скачать", "Download tracks to play them without a network. ⋯ › Download"),
    ("DownloadsResume", "Возобновить", "Resume"),
    ("DownloadsWaitingTitle", "Загрузки ждут", "Downloads are waiting"),
    ("DropImport", "Импорт копии", "Import a copy"),
    ("DropOpen", "Открыть в Melogold", "Open in Melogold"),
    ("DurationHoursMinutesFormat", "{0} ч {1} мин", "{0} h {1} min"),
    ("DurationMinutesFormat", "{0} мин", "{0} min"),
    ("EmptySearchHistory", "История пуста", "History is empty"),
    ("ErrorBlocked", "YouTube не ответил: проверка на бота или блокировка. Попробуйте позже или смените сеть", "YouTube didn't respond: a bot check or a block. Try again later or switch networks"),
    ("ErrorOffline", "Нет соединения с YouTube. Проверьте сеть или VPN", "Can't reach YouTube. Check your network or VPN"),
    ("ErrorParser", "YouTube изменил страницу. Исправление придёт с обновлением", "YouTube changed its page. A fix will come with an update"),
    ("ErrorUnknown", "Что-то пошло не так", "Something went wrong"),
    ("Explicit", "Откровенный текст", "Explicit"),
    ("Favorites", "Избранное", "Favorites"),
    ("FavoritesEmpty", "Здесь будет ваша музыка", "Your music will be here"),
    ("FavoritesEmptyHint", "Нажимайте ♡ — треки появятся здесь", "Tap ♡ and tracks will show up here"),
    ("Filter", "Фильтр", "Filter"),
    ("FindMusic", "Найти музыку", "Find music"),
    ("ForYou", "Для вас", "For you"),
    ("GeoOtherCountries_few", "в {0} других странах", "in {0} other countries"),
    ("GeoOtherCountries_many", "в {0} других странах", "in {0} other countries"),
    ("GeoOtherCountries_one", "в {0} другой стране", "in {0} other country"),
    ("GeoOtherCountries_other", "в {0} других странах", "in {0} other countries"),
    ("History", "История", "History"),
    ("HistoryCleared", "История очищена", "History cleared"),
    ("HistoryDeviceAll", "Все устройства", "All devices"),
    ("HistoryDeviceChoose", "Чьи прослушивания показать", "Whose plays to show"),
    ("HistoryDeviceThis", "Это устройство", "This device"),
    ("HistoryEmpty", "Истории пока нет", "No history yet"),
    ("HistoryEmptyHint", "Послушайте что-нибудь — история появится здесь", "Play something and your history will show up here"),
    ("HistoryHint", "Недавние · Чаще всего", "Recent · Most played"),
    ("HistoryMostPlayed", "Чаще всего", "Most played"),
    ("HistoryRecent", "Недавние", "Recent"),
    ("HoursAgo_few", "{0} часа назад", "{0} hours ago"),
    ("HoursAgo_many", "{0} часов назад", "{0} hours ago"),
    ("HoursAgo_one", "{0} час назад", "{0} hour ago"),
    ("HoursAgo_other", "{0} часа назад", "{0} hours ago"),
    ("ImageCacheSizeBox.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Максимальный размер кэша изображений", "Image cache max size"),
    ("ImportDatesSkippedFormat", "Прослушивания и лайки с невозможными датами пропущены: {0}.", "Plays and likes with impossible dates are left out: {0}."),
    ("ImportDoneOk", "Готово", "OK"),
    ("ImportDoneTitle", "Библиотека импортирована", "Library imported"),
    ("ImportFailedTitle", "Не удалось импортировать", "Could not import"),
    ("ImportLocalSkippedFormat", "Локальные файлы не перенесены: {0}.", "Local files are not moved: {0}."),
    ("ImportNotBackup", "Это не копия ViTune, ViMusic или Melogold.", "This is not a ViTune, ViMusic or Melogold backup."),
    ("ImportOpenHistory", "Открыть историю", "Open history"),
    ("ImportPlaysKnownFormat", "Прослушивания, которые уже были, не повторяются: {0}.", "Plays that were already here are not repeated: {0}."),
    ("ImportRunning", "Импортируем библиотеку…", "Importing the library…"),
    ("ImportSummaryFormat", "Новых треков — {0}, прослушиваний — {1}, в Избранном — {2}, текстов — {3}, плейлистов — {4}, сохранённых альбомов и исполнителей — {5}.", "New tracks: {0}. Plays: {1}. Favorites: {2}. Lyrics: {3}. Playlists: {4}. Saved albums and artists: {5}."),
    ("ImportSyncNote", "На другие устройства история уйдёт через сервер постепенно — до 2000 прослушиваний в час.", "The history goes to your other devices through the server bit by bit: up to 2000 plays an hour."),
    ("ImportTooOld", "Эта копия слишком старая.", "This backup is too old to read."),
    ("ImportUnreadable", "Файл не читается. Возможно, он повреждён.", "The file could not be read. It may be damaged."),
    ("ImportUnsupported", "Копии InnerTune, Metrolist и похожих приложений пока не поддерживаются.", "Backups of InnerTune, Metrolist and similar apps are not supported yet."),
    ("InLibrary", "В библиотеке", "In library"),
    ("InLibraryCheck", "В библиотеке", "In library"),
    ("JustNow", "только что", "just now"),
    ("KeyMenu", "Меню", "Menu"),
    ("KeySpace", "Пробел", "Space"),
    ("LibraryHeader", "Библиотека", "Library"),
    ("LibraryImport", "Импорт из ViTune или ViMusic", "Import from ViTune or ViMusic"),
    ("LibraryImportDescription", "Треки, история, Избранное, плейлисты и тексты добавятся к библиотеке", "Tracks, history, favorites, playlists and lyrics join your library"),
    ("LibraryTitle.Text", "Библиотека", "Library"),
    ("LicensesServices", "Звук и каталог — YouTube и YouTube Music; тексты — LRCLIB и KuGou. Melogold не связан с ними.", "Audio and catalog come from YouTube and YouTube Music; lyrics from LRCLIB and KuGou. Melogold isn't affiliated with them."),
    ("LicensesTitle", "Лицензии", "Licenses"),
    ("LikedCountFormat", "В Избранное: {0}", "Added to Favorites: {0}"),
    ("LinkAlreadyClaimed", "Этот код уже используется", "This code is already in use"),
    ("LinkApprovedFormat", "«{0}» вошло в аккаунт", "“{0}” signed in to your account"),
    ("LinkChooseNumber", "Выберите число, которое видно на новом устройстве", "Choose the number shown on the new device"),
    ("LinkCodeHeader", "Код", "Code"),
    ("LinkCodeText", "Введите код, который показывает новое устройство — например, часы", "Enter the code the new device shows — for example, your watch"),
    ("LinkContinue", "Продолжить", "Continue"),
    ("LinkCopied", "Ссылка скопирована", "Link copied"),
    ("LinkDenied", "Вход отклонён", "Sign-in denied"),
    ("LinkDeny", "Отклонить", "Deny"),
    ("LinkExpired", "Код устарел — запросите новый на устройстве", "The code has expired — get a new one on the device"),
    ("LinkExpiresFormat", "Код действует ещё {0} мин", "The code works for {0} more min"),
    ("LinkImportLater", "Импорт плейлистов из других сервисов появится позже", "Importing playlists from other services is coming later"),
    ("LinkInvalidCode", "Код — 8 букв и цифр, например K7QX-M2PD", "The code is 8 letters and digits, like K7QX-M2PD"),
    ("LinkInviteCancelled", "Приглашение отменено", "The invitation was canceled"),
    ("LinkInviteExpired", "Код устарел. Покажите новый", "The code has expired. Show a new one"),
    ("LinkInviteText", "На новом устройстве выберите «Войти по коду» и «У меня есть код с другого устройства», затем введите этот код", "On the new device, choose “Sign in with a code” and “I have a code from another device”, then enter this code"),
    ("LinkKindAlbum", "альбом", "album"),
    ("LinkKindChannel", "канал", "channel"),
    ("LinkKindPlaylist", "плейлист", "playlist"),
    ("LinkKindShare", "плейлист Melogold", "Melogold playlist"),
    ("LinkKindVideo", "видео YouTube", "YouTube video"),
    ("LinkLookingFormat", "Ищем ссылку {0} на YouTube Music…", "Looking for the {0} link on YouTube Music…"),
    ("LinkNotFound", "Код не найден", "Code not found"),
    ("LinkOtherNetwork", "В другой сети — убедитесь, что это ваше устройство", "On another network — make sure it's your device"),
    ("LinkSameNetwork", "В той же сети", "On the same network"),
    ("LinkShowCode", "Показать код для нового устройства", "Show a code for a new device"),
    ("LinkUnsupported", "Эту ссылку не открыть", "This link can't be opened"),
    ("LinkVerifyMismatch", "Число не совпало — вход отклонён", "The number didn’t match — sign-in denied"),
    ("LinkWaitingNew", "Ждём новое устройство…", "Waiting for the new device…"),
    ("LinkWrongMode", "Это код приглашения, а не входа", "This is an invitation code, not a sign-in code"),
    ("Live", "В ЭФИРЕ", "LIVE"),
    ("LyricsEarlier01", "Раньше на 0,1 с", "0.1 s earlier"),
    ("LyricsEarlier05", "Раньше на 0,5 с", "0.5 s earlier"),
    ("LyricsEdit", "Редактировать текст", "Edit lyrics"),
    ("LyricsEditorAllMarked", "Всё отмечено", "Everything is marked"),
    ("LyricsEditorBacking", "Подпевка…", "Backing vocals…"),
    ("LyricsEditorBackingLabel", "Подпевка", "Backing vocals"),
    ("LyricsEditorClearTime", "Сбросить время", "Clear time"),
    ("LyricsEditorDiscard", "Закрыть", "Close"),
    ("LyricsEditorDiscardTitle", "Закрыть без сохранения?", "Close without saving?"),
    ("LyricsEditorEarlier", "Раньше на 0,1 с", "0.1 s earlier"),
    ("LyricsEditorEndLine", "Конец строки", "End line"),
    ("LyricsEditorExportLrc", "Экспорт в LRC…", "Export as LRC…"),
    ("LyricsEditorExportTtml", "Экспорт в TTML…", "Export as TTML…"),
    ("LyricsEditorExported", "Файл сохранён", "File saved"),
    ("LyricsEditorKeysHint", "Enter — отметить · Shift+Enter — конец строки · Backspace — заново · F1 — все клавиши", "Enter — mark · Shift+Enter — end line · Backspace — redo · F1 — all keys"),
    ("LyricsEditorLanguage", "Язык текста…", "Lyrics language…"),
    ("LyricsEditorLanguageLabel", "Код, например ru", "Code, e.g. en"),
    ("LyricsEditorLanguageTitle", "Язык", "Language"),
    ("LyricsEditorLater", "Позже на 0,1 с", "0.1 s later"),
    ("LyricsEditorLineLanguage", "Язык строки…", "Line language…"),
    ("LyricsEditorLines", "Строки", "Lines"),
    ("LyricsEditorMark", "Отметить", "Mark"),
    ("LyricsEditorNextFormat", "Далее: {0}", "Next: {0}"),
    ("LyricsEditorNextLabel", "Далее", "Next"),
    ("LyricsEditorNoLines", "Сначала добавьте текст на вкладке «Текст»", "Add the lyrics on the Text tab first"),
    ("LyricsEditorNoTime", "—", "—"),
    ("LyricsEditorRewind", "Назад на 3 с", "Back 3 s"),
    ("LyricsEditorSave", "Сохранить", "Save"),
    ("LyricsEditorSaved", "Текст сохранён", "Lyrics saved"),
    ("LyricsEditorSide", "Сторона исполнителя", "Singer side"),
    ("LyricsEditorSideEnd", "Справа", "Right"),
    ("LyricsEditorSideStart", "Слева", "Left"),
    ("LyricsEditorTabPreview", "Просмотр", "Preview"),
    ("LyricsEditorTabSync", "Синхронизация", "Sync"),
    ("LyricsEditorTabText", "Текст", "Text"),
    ("LyricsEditorTextHint", "Каждая строка песни — с новой строки. Подпевку пишите в скобках в конце строки.", "One line of the song per line. Put backing vocals in parentheses at the end of a line."),
    ("LyricsEditorTextLabel", "Текст песни", "Lyrics"),
    ("LyricsEditorTitle", "Текст песни", "Lyrics"),
    ("LyricsEditorUndo", "Отменить", "Undo"),
    ("LyricsEditorWords", "Слова", "Words"),
    ("LyricsFind", "Найти текст", "Find lyrics"),
    ("LyricsFindMenu", "Найти другой текст…", "Find other lyrics…"),
    ("LyricsImportFailed", "Не удалось прочитать текст из файла", "Couldn't read lyrics from the file"),
    ("LyricsImportFile", "Импорт из файла", "Import from file"),
    ("LyricsImported", "Текст добавлен", "Lyrics added"),
    ("LyricsInstrumental", "Проигрыш", "Instrumental"),
    ("LyricsJumpToLine", "К текущей строке", "Back to the current line"),
    ("LyricsLater01", "Позже на 0,1 с", "0.1 s later"),
    ("LyricsLater05", "Позже на 0,5 с", "0.5 s later"),
    ("LyricsLoadFailed", "Не удалось загрузить текст", "Couldn't load the lyrics"),
    ("LyricsLoading", "Загрузка текста", "Loading lyrics"),
    ("LyricsOffset", "Сдвиг текста", "Lyrics offset"),
    ("LyricsOffsetFormat", "Сдвиг текста · {0} с", "Lyrics offset · {0} s"),
    ("LyricsResetShiftFormat", "Сбросить сдвиг ({0} с)", "Reset the shift ({0} s)"),
    ("LyricsResultPlain", "Без синхронизации", "Unsynced"),
    ("LyricsResultSynced", "Синхронизированный", "Synced"),
    ("LyricsShowPlain", "Текст без синхронизации", "Unsynced lyrics"),
    ("LyricsShowSynced", "Синхронизированный текст", "Synced lyrics"),
    ("LyricsSourceFile", "Текст импортирован из файла", "Lyrics imported from a file"),
    ("LyricsSourceKuGou", "Текст: KuGou", "Lyrics: KuGou"),
    ("LyricsSourceLrcLib", "Текст: LRCLIB", "Lyrics: LRCLIB"),
    ("LyricsSourceMelogold", "Текст: сообщество Melogold", "Lyrics: Melogold community"),
    ("LyricsSourceUser", "Ваш текст", "Your lyrics"),
    ("LyricsSourceYouTubeMusic", "Текст: YouTube Music", "Lyrics: YouTube Music"),
    ("LyricsTooLarge", "Текст слишком большой для сервера: он останется только на этом устройстве", "The lyrics are too large for the server: they stay on this device only"),
    ("LyricsUnavailable", "Текст песни недоступен", "Lyrics are not available"),
    ("MenuAddToPlaylist", "Добавить в плейлист…", "Add to playlist…"),
    ("MenuAddToQueue", "В конец очереди", "Add to queue"),
    ("MenuCopyLink", "Скопировать ссылку", "Copy link"),
    ("MenuDontShow", "Не показывать этот трек", "Don't show this track"),
    ("MenuDownload", "Скачать", "Download"),
    ("MenuDownloadCancel", "Скачивается · Отменить", "Downloading · Cancel"),
    ("MenuDownloadCancelFormat", "Скачивается {0} % · Отменить", "Downloading {0}% · Cancel"),
    ("MenuDownloadCancelWaiting", "Отменить загрузку", "Cancel download"),
    ("MenuDownloadLive", "Трансляцию нельзя скачать", "Live streams can't be downloaded"),
    ("MenuDownloadRemove", "Удалить загрузку", "Remove download"),
    ("MenuDownloadResume", "Возобновить загрузки", "Resume downloads"),
    ("MenuDownloadRetry", "Скачать снова", "Download again"),
    ("MenuEditDetails", "Изменить сведения…", "Edit details…"),
    ("MenuFavoriteAdd", "В Избранное", "Add to Favorites"),
    ("MenuFavoriteRemove", "Убрать из Избранного", "Remove from Favorites"),
    ("MenuGoToAlbum", "Открыть альбом", "Go to album"),
    ("MenuGoToArtist", "Открыть исполнителя", "Go to artist"),
    ("MenuGoToChannel", "Открыть канал", "Go to channel"),
    ("MenuOtherVersions", "Другие версии", "Other versions"),
    ("MenuPlayNext", "Играть следующим", "Play next"),
    ("MenuRemoveFromHistory", "Убрать из истории", "Remove from history"),
    ("MenuRemoveFromPlaylist", "Убрать из плейлиста", "Remove from playlist"),
    ("MenuRemoveFromQueue", "Убрать из очереди", "Remove from queue"),
    ("MenuSaveFile", "Сохранить файлом", "Save as file"),
    ("MenuShare", "Поделиться", "Share"),
    ("MenuShortcuts", "Сочетания клавиш", "Keyboard shortcuts"),
    ("MenuShowAgain", "Снова показывать этот трек", "Show this track again"),
    ("MenuStartRadio", "Включить радио", "Start radio"),
    ("MenuStreamInfo", "Сведения о потоке", "Stream info"),
    ("MenuTrackRadio", "Включить радио по треку", "Start track radio"),
    ("MiniPlayerExpand", "Развернуть", "Expand"),
    ("MinutesAgo_few", "{0} минуты назад", "{0} minutes ago"),
    ("MinutesAgo_many", "{0} минут назад", "{0} minutes ago"),
    ("MinutesAgo_one", "{0} минуту назад", "{0} minute ago"),
    ("MinutesAgo_other", "{0} минуты назад", "{0} minutes ago"),
    ("MinutesLeft_few", "осталось {0} минуты", "{0} minutes left"),
    ("MinutesLeft_many", "осталось {0} минут", "{0} minutes left"),
    ("MinutesLeft_one", "осталась {0} минута", "{0} minute left"),
    ("MinutesLeft_other", "осталось {0} минуты", "{0} minutes left"),
    ("Minutes_few", "{0} минуты", "{0} minutes"),
    ("Minutes_many", "{0} минут", "{0} minutes"),
    ("Minutes_one", "{0} минута", "{0} minute"),
    ("Minutes_other", "{0} минуты", "{0} minutes"),
    ("MoreOptions", "Другие действия", "More options"),
    ("MyShares", "Мои ссылки", "My links"),
    ("MySharesEmpty", "Ссылок пока нет", "No links yet"),
    ("MySharesEmptyHint", "Откройте свой плейлист и выберите «Поделиться» в меню", "Open your playlist and choose “Share” in its menu"),
    ("MySharesText", "Ссылки на ваши плейлисты: по ним слушают и сохраняют себе", "Links to your playlists: people listen and save them"),
    ("NavLibrary.AccessKey", "Б", "L"),
    ("NavLibrary.Content", "Библиотека", "Library"),
    ("NavNew.AccessKey", "Н", "N"),
    ("NavNew.Content", "Новое", "New"),
    ("NavSettings", "Настройки", "Settings"),
    ("NavTrends.AccessKey", "Т", "T"),
    ("NavTrends.Content", "Тренды", "Trends"),
    ("NewHeader", "Новое", "New"),
    ("NewPlaylist", "Новый плейлист", "New playlist"),
    ("NewPlaylistName", "Название", "Name"),
    ("NewReleases", "Новые альбомы и синглы", "New albums & singles"),
    ("NewTitle.Text", "Новое", "New"),
    ("Next", "Следующий трек", "Next track"),
    ("NoAccountText", "Вход нужен только для синхронизации между устройствами", "You only need to sign in to sync between devices"),
    ("NoAccountTitle", "Melogold работает без аккаунта", "Melogold works without an account"),
    ("NoLyricsFound", "Тексты песен не найдены", "No lyrics found"),
    ("NoNetwork", "Нет сети", "No network"),
    ("NoPlaylistsHint", "Здесь появятся ваши плейлисты", "Your playlists will appear here"),
    ("NoPlaylistsYet", "Плейлистов пока нет", "No playlists yet"),
    ("NothingFound", "Ничего не нашлось", "Nothing found"),
    ("NothingToDownload", "Выделенное уже скачано", "The selection is already downloaded"),
    ("NowPlaying", "Сейчас играет", "Now playing"),
    ("NowPlayingArtwork", "Обложка", "Artwork"),
    ("OfflineDataFromFormat", "Нет сети — данные от {0}", "No connection — data from {0}"),
    ("OfflineSince", "Нет сети — данные от {0}", "Offline — data from {0}"),
    ("OpenAction", "Открыть", "Open"),
    ("OpenLinkFormat", "Открыть ссылку: {0}", "Open link: {0}"),
    ("OpenLogs.Content", "Открыть папку", "Open folder"),
    ("OpenSource.Content", "Открыть", "Open"),
    ("Pause", "Пауза", "Pause"),
    ("Play", "Воспроизвести", "Play"),
    ("PlayAll", "Слушать", "Play"),
    ("PlayAllForYou", "Слушать всё", "Play all"),
    ("PlayErrorAge", "Нужна проверка возраста — пока не поддерживается", "Age verification is required — not supported yet"),
    ("PlayErrorBot", "YouTube просит подтвердить, что вы не бот: он временно не пускает адрес, с которого вы выходите в сеть. С VPN выберите другой сервер, без VPN — подождите несколько часов.", "YouTube asks to confirm you're not a bot: it is temporarily blocking the address you go online from. With a VPN, pick another server; without one, wait a few hours."),
    ("PlayErrorBotShort", "YouTube не пускает этот адрес — смените сервер VPN", "YouTube is blocking this address — switch VPN server"),
    ("PlayErrorExtractor", "Не удалось получить поток", "Couldn't get the stream"),
    ("PlayErrorGeo", "Недоступно в вашей стране", "Unavailable in your country"),
    ("PlayErrorGeoCountryFormat", "Недоступно в стране «{0}»: YouTube считает, что вы там, а правообладатель закрыл трек для этой страны. С VPN выберите сервер другой страны: некоторые серверы YouTube тоже относит к стране «{0}».", "Unavailable in {0}: YouTube places you there, and the rights holder closed this track for it. With a VPN, pick a server in another country: YouTube counts some VPN servers as {0} too."),
    ("PlayErrorGeoCountryNoticeFormat", "Недоступно в стране «{0}»", "Unavailable in {0}"),
    ("PlayErrorGeoCountryOpenFormat", "Недоступно в стране «{0}»: YouTube считает, что вы там, а правообладатель открыл трек {1}. С VPN выберите сервер другой страны: некоторые серверы YouTube тоже относит к стране «{0}».", "Unavailable in {0}: YouTube places you there, and the rights holder opened this track {1}. With a VPN, pick a server in another country: YouTube counts some VPN servers as {0} too."),
    ("PlayErrorGeoCountryShortFormat", "Недоступно: {0}", "Unavailable in {0}"),
    ("PlayErrorNetwork", "Нет соединения. Проверьте сеть или VPN", "No connection. Check your network or VPN"),
    ("PlayErrorUnavailable", "Видео удалено или закрыто", "The video was removed or made private"),
    ("PlayerArtwork.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Сейчас играет", "Now playing"),
    ("PlayerDeviceButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Устройство", "Device"),
    ("PlayerDeviceButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Устройство", "Device"),
    ("PlayerLike.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "В Избранное", "Add to Favorites"),
    ("PlayerLike.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "В Избранное (Ctrl+D)", "Add to Favorites (Ctrl+D)"),
    ("PlayerLyrics", "Текст", "Lyrics"),
    ("PlayerLyricsButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Текст", "Lyrics"),
    ("PlayerLyricsButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Текст (Ctrl+L)", "Lyrics (Ctrl+L)"),
    ("PlayerMiniButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Мини-плеер", "Mini player"),
    ("PlayerMiniButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Мини-плеер (Ctrl+Shift+M)", "Mini player (Ctrl+Shift+M)"),
    ("PlayerMore.AccessKey", "Е", "M"),
    ("PlayerMore.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Ещё", "More"),
    ("PlayerMore.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Ещё", "More"),
    ("PlayerMute.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Без звука", "Mute"),
    ("PlayerMute.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Без звука (Ctrl+M)", "Mute (Ctrl+M)"),
    ("PlayerNext.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Следующий трек", "Next track"),
    ("PlayerNext.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Следующий трек (Ctrl+→)", "Next track (Ctrl+→)"),
    ("PlayerPrevious.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Предыдущий трек", "Previous track"),
    ("PlayerPrevious.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Предыдущий трек (Ctrl+←)", "Previous track (Ctrl+←)"),
    ("PlayerQueueButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Очередь", "Queue"),
    ("PlayerQueueButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Очередь (Ctrl+Q)", "Queue (Ctrl+Q)"),
    ("PlayerSeek.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Перемотка", "Seek"),
    ("PlayerShuffle.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Перемешать", "Shuffle"),
    ("PlayerShuffle.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Перемешать (Ctrl+H)", "Shuffle (Ctrl+H)"),
    ("PlayerVolume.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Громкость", "Volume"),
    ("PlayerVolumeButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Громкость", "Volume"),
    ("PlayerVolumeButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Громкость (колесо мыши меняет её)", "Volume (mouse wheel changes it)"),
    ("PlayingNextFormat", "Играет следующим: {0}", "Playing next: {0}"),
    ("PlayingNextTracks_few", "Играют следующими: {0} трека", "Playing next: {0} tracks"),
    ("PlayingNextTracks_many", "Играют следующими: {0} треков", "Playing next: {0} tracks"),
    ("PlayingNextTracks_one", "Играет следующим: {0} трек", "Playing next: {0} track"),
    ("PlayingNextTracks_other", "Играют следующими: {0} трека", "Playing next: {0} tracks"),
    ("PlaylistCreatedFormat", "Плейлист «{0}»: {1}", "Playlist “{0}”: {1}"),
    ("PlaylistDeletedFormat", "Плейлист «{0}» удалён", "Playlist “{0}” deleted"),
    ("PlaylistEmpty", "В плейлисте пока пусто", "This playlist is empty"),
    ("PlaylistEmptyHint", "Добавляйте треки через «Добавить в плейлист…» в меню трека", "Add tracks with “Add to playlist…” in the track menu"),
    ("PlaylistGone", "Плейлист удалён", "The playlist was deleted"),
    ("PlaylistsForYou", "Плейлисты для вас", "Playlists for you"),
    ("Previous", "Предыдущий трек", "Previous track"),
    ("QueueActions", "Действия с очередью", "Queue actions"),
    ("QueueClear", "Очистить", "Clear"),
    ("QueueCleared", "Очередь очищена", "Queue cleared"),
    ("QueueNowPlaying", "Сейчас играет", "Now playing"),
    ("QueueRemoved", "Убрано из очереди", "Removed from the queue"),
    ("QueueReplaced", "Очередь заменена", "Queue replaced"),
    ("QueueSaveAsPlaylist", "Сохранить как плейлист", "Save as playlist"),
    ("QueueSavedFormat", "Сохранено как «{0}»", "Saved as “{0}”"),
    ("QueueSimilar", "Далее — похожие", "Up next — similar"),
    ("QueueTitle", "Очередь", "Queue"),
    ("QueueUpNext", "Далее", "Up next"),
    ("QueuedCountFormat", "В конец очереди: {0}", "Added to queue: {0}"),
    ("RecentQueries", "Недавние запросы", "Recent searches"),
    ("Refresh", "Обновить", "Refresh"),
    ("RemoteChosen", "Выбрано", "Selected"),
    ("RemoteControlledByFormat", "Управляет «{0}»", "“{0}” is in control"),
    ("RemoteDevice", "Устройство", "Device"),
    ("RemoteDisabledFormat", "На „{0}“ управление выключено", "Control is off on “{0}”"),
    ("RemoteDisconnect.Content", "Отключиться", "Disconnect"),
    ("RemoteListenHere.Content", "Слушать здесь", "Listen here"),
    ("RemoteNoOtherDevices", "Других устройств в аккаунте нет", "No other devices in the account"),
    ("RemoteNotControllable", "Управление выключено", "Control is off"),
    ("RemoteNothingFormat", "На «{0}» ничего не играет", "Nothing is playing on “{0}”"),
    ("RemoteNothingPlaying", "Ничего не играет", "Nothing is playing"),
    ("RemoteOffline", "Не в сети", "Offline"),
    ("RemoteOfflineFormat", "„{0}“ не в сети", "“{0}” is offline"),
    ("RemoteOnline", "В сети", "Online"),
    ("RemoteOtherDevices", "Другие устройства", "Other devices"),
    ("RemotePlayingOnFormat", "Играет на «{0}»", "Playing on “{0}”"),
    ("RemoteSystemSound", "Вывод звука в Windows", "Windows sound output"),
    ("RemoteThisDevice", "Это устройство", "This device"),
    ("RemoteVolumeFormat", "громкость {0}", "volume {0}"),
    ("RemoveDownloadsButton.Content", "Удалить все", "Remove all"),
    ("RemovedFromHistoryEverywhereFormat", "Убрано из истории на всех устройствах: «{0}»", "Removed from history on all devices: “{0}”"),
    ("RemovedFromHistoryFormat", "Убрано из истории: «{0}»", "Removed from history: “{0}”"),
    ("RemovedFromPlaylistFormat", "Убрано из плейлиста: «{0}»", "Removed from playlist: “{0}”"),
    ("Rename", "Переименовать", "Rename"),
    ("RepeatAll", "Повтор очереди", "Repeat queue"),
    ("RepeatOff", "Повтор выключен", "Repeat off"),
    ("RepeatOne", "Повтор трека", "Repeat track"),
    ("ResetHiddenButton.Content", "Сбросить", "Reset"),
    ("ResolvingText.Text", "Получаем поток…", "Getting the stream…"),
    ("ResultsAlbums", "Альбомы", "Albums"),
    ("ResultsAll", "Всё", "All"),
    ("ResultsArtists", "Исполнители", "Artists"),
    ("ResultsChannels", "Каналы", "Channels"),
    ("ResultsLive", "Трансляции", "Live"),
    ("ResultsMore", "Ещё", "More"),
    ("ResultsMusic", "Музыка", "Music"),
    ("ResultsMusicVideos", "Клипы", "Music videos"),
    ("ResultsNothing", "Ничего не нашлось. Проверьте написание или посмотрите на YouTube", "Nothing found. Check the spelling or look on YouTube"),
    ("ResultsNothingInCatalog", "В каталоге YouTube Music ничего не нашлось — вот что есть на YouTube", "Nothing in the YouTube Music catalog — here's what's on YouTube"),
    ("ResultsOpen", "Открыть", "Open"),
    ("ResultsPlaylists", "Плейлисты", "Playlists"),
    ("ResultsSearchYouTube", "Искать на YouTube", "Search YouTube"),
    ("ResultsSongs", "Песни", "Songs"),
    ("ResultsTopResult", "Лучший результат", "Top result"),
    ("ResultsVideos", "Видео", "Videos"),
    ("ResultsYouTube", "YouTube", "YouTube"),
    ("Retry", "Повторить", "Retry"),
    ("RetryLink.Content", "Повторить", "Retry"),
    ("RowCached.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Есть без сети (в кэше)", "Available offline (cached)"),
    ("RowCachedTooltip", "Есть без сети (в кэше)", "Available offline (cached)"),
    ("RowLike.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "В Избранное", "Add to Favorites"),
    ("RowMenu", "Меню", "Menu"),
    ("RowMenuButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Меню", "Menu"),
    ("RowMenuButton.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip", "Меню", "Menu"),
    ("RowPlay", "Воспроизвести", "Play"),
    ("RowPlayButton.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Воспроизвести", "Play"),
    ("SaveAsPlaylist", "Сохранить", "Save"),
    ("SaveFileDone", "Файл сохранён", "File saved"),
    ("SaveFileFailedFormat", "Не удалось сохранить «{0}»", "Couldn’t save “{0}”"),
    ("SaveFileOpen", "Открыть", "Open"),
    ("SaveFileStartedFormat", "Сохраняем «{0}»…", "Saving “{0}”…"),
    ("SaveFileType", "Аудио M4A", "M4A audio"),
    ("SaveToLibrary", "Сохранить", "Save"),
    ("SavedToLibraryFormat", "Сохранено в Библиотеку: „{0}“", "Saved to Library: “{0}”"),
    ("SearchBox.AccessKey", "П", "F"),
    ("SearchBox.PlaceholderText", "Поиск", "Search"),
    ("SeeAll", "Все", "See all"),
    ("SelectionAddToPlaylist", "Добавить в плейлист…", "Add to playlist…"),
    ("SelectionAlbumSetFormat", "Альбом указан: {0}", "Album set: {0}"),
    ("SelectionClear", "Снять выделение", "Clear selection"),
    ("SelectionCountFormat", "Выбрано: {0}", "{0} selected"),
    ("SelectionDownload", "Скачать", "Download"),
    ("SelectionLike", "В Избранное", "Add to Favorites"),
    ("SelectionNewPlaylist", "Новый плейлист…", "New playlist…"),
    ("SelectionPlay", "Слушать", "Play"),
    ("SelectionQueue", "В конец очереди", "Add to queue"),
    ("SelectionSelectAll", "Выбрать все", "Select all"),
    ("SelectionSetAlbum", "Указать альбом…", "Set album…"),
    ("SelectionSetAlbumTitle", "Указать альбом", "Set album"),
    ("ServerAddress", "Адрес сервера", "Server address"),
    ("ServerCheck", "Проверить", "Check"),
    ("ServerClientOutdated", "Этому серверу нужна более новая версия Melogold", "This server needs a newer version of Melogold"),
    ("ServerConnect", "Подключить", "Connect"),
    ("ServerCurrent", "Используется", "In use"),
    ("ServerDefault", "Сервер по умолчанию", "Default server"),
    ("ServerErrorMalformed", "Это не похоже на адрес сервера", "This doesn't look like a server address"),
    ("ServerErrorParams", "Адрес не должен содержать логин, параметры или #", "The address can't contain a login, parameters or #"),
    ("ServerErrorScheme", "Адрес начинается с https:// или http://", "The address starts with https:// or http://"),
    ("ServerHttpsNeeded", "Адрес в интернете должен начинаться с https://", "An internet address must start with https://"),
    ("ServerInfoFormat", "{0} · версия {1}", "{0} · version {1}"),
    ("ServerInsecure", "Незащищённое соединение: только для домашней сети", "Not a secure connection: use it only at home"),
    ("ServerNotMelogold", "Это не сервер Melogold", "This is not a Melogold server"),
    ("ServerRegistrationClosed", "Регистрация закрыта", "Registration is closed"),
    ("ServerRegistrationFirst", "Регистрация открыта для первого аккаунта", "Registration is open for the first account"),
    ("ServerRegistrationOpen", "Регистрация открыта", "Registration is open"),
    ("ServerSwitchSignsOut", "После смены сервера нужно будет войти заново", "After switching servers you will sign in again"),
    ("ServerText", "Библиотека синхронизируется через этот сервер. Можно указать свой — сервер открытый и ставится одной командой", "Your library syncs through this server. You can use your own: the server is open source and installs with one command"),
    ("ServerTitle", "Сервер Melogold", "Melogold server"),
    ("ServerTooOld", "Сервер слишком старый для этой версии Melogold", "The server is too old for this version of Melogold"),
    ("ServerUnreachable", "Сервер не отвечает", "The server doesn't answer"),
    ("ServiceYandexMusic", "Яндекс Музыка", "Yandex Music"),
    ("SettingsAbout.Text", "О приложении", "About"),
    ("SettingsAppearance.Text", "Внешний вид", "Appearance"),
    ("SettingsBackup.Description", "Один файл с треками, историей, Избранным, плейлистами и текстами — его открывает Melogold на Android, Windows и Apple. Настройки и кэш в копию не входят", "One file with tracks, history, Favorites, playlists and lyrics that Melogold on Android, Windows and Apple opens. Settings and the cache are not included"),
    ("SettingsBackup.Header", "Сохранить копию", "Save a copy"),
    ("SettingsCache.Header", "Другой кэш", "Other cache"),
    ("SettingsDatabase.Text", "База данных", "Database"),
    ("SettingsDiagnostics.Description", "Журналы приложения: пригодятся, если что-то не работает", "App logs, useful if something doesn't work"),
    ("SettingsDiagnostics.Header", "Диагностика", "Diagnostics"),
    ("SettingsDownloads.Header", "Загрузки", "Downloads"),
    ("SettingsDownloadsDelete", "Удалить", "Remove"),
    ("SettingsDownloadsDeleteAllTextFormat", "{0}, {1}. Треки останутся в библиотеке, но без сети играть не будут.", "{0}, {1}. The tracks stay in the library but won't play without a network."),
    ("SettingsDownloadsDeleteAllTitle", "Удалить все загрузки?", "Remove all downloads?"),
    ("SettingsDownloadsEmpty", "Скачанного нет · ⋯ › Скачать у трека", "Nothing downloaded · ⋯ › Download on a track"),
    ("SettingsHidden.Header", "Сбросить черный список", "Reset the blacklist"),
    ("SettingsImageCache.Header", "Кэш изображений", "Image cache"),
    ("SettingsImageCacheSize.Header", "Максимальный размер", "Max size"),
    ("SettingsLibrary.Text", "Библиотека и история", "Library and history"),
    ("SettingsLicenses.Description", "Программы с открытым кодом в Melogold", "Open source software in Melogold"),
    ("SettingsLicenses.Header", "Лицензии", "Licenses"),
    ("SettingsNormalize.Description", "Регулирует громкость до фиксированного уровня", "Keeps every track at the same loudness"),
    ("SettingsNormalize.Header", "Нормализация громкости", "Loudness normalization"),
    ("SettingsPauseHistory.Description", "Прослушивания не попадают в историю и «Для вас»", "Plays don't go into History and For you"),
    ("SettingsPauseHistory.Header", "Приостановить историю воспроизведений", "Pause playback history"),
    ("SettingsPauseSearch.Description", "Не сохраняет новые поисковые запросы и не показывает историю", "Doesn't save new searches or show the history"),
    ("SettingsPauseSearch.Header", "Приостановить историю поиска", "Pause search history"),
    ("SettingsPlayback.Text", "Воспроизведение", "Playback"),
    ("SettingsRemoteControl.Description", "Пауза, следующий трек и громкость — с телефона или другого компьютера", "Pause, skip and change the volume from your phone or another computer"),
    ("SettingsRemoteControl.Header", "Управление с других устройств", "Control from other devices"),
    ("SettingsReportBug.Description", "Если вам нужна помощь с ошибкой, вы можете оставить запрос на GitHub", "If you need help with a bug you can file an issue on GitHub"),
    ("SettingsReportBug.Header", "Сообщить о проблеме", "Report an issue"),
    ("SettingsRequestFeature.Description", "Вы будете перенаправлены на GitHub", "You will be redirected to GitHub"),
    ("SettingsRequestFeature.Header", "Запросить функцию или предложить идею", "Request a feature or suggest an idea"),
    ("SettingsRestore.Description", "Копия ViTune, ViMusic или Melogold добавится к библиотеке. Ничего не удаляется", "A ViTune, ViMusic or Melogold backup is added to your library. Nothing here is deleted"),
    ("SettingsRestore.Header", "Импорт копии", "Import a copy"),
    ("SettingsSearchHistory.Header", "Очистить историю поиска", "Clear search history"),
    ("SettingsServer.Header", "Сервер Melogold", "Melogold server"),
    ("SettingsShortcuts.Description", "Все клавиши клиента · F1 или Ctrl+/", "All keys of the app · F1 or Ctrl+/"),
    ("SettingsShortcuts.Header", "Сочетания клавиш", "Keyboard shortcuts"),
    ("SettingsSongCache.Header", "Кэш музыки", "Music cache"),
    ("SettingsSongCacheSize.Header", "Размер кэша", "Cache size"),
    ("SettingsSource.Description", "Просмотреть исходный код", "View the source code"),
    ("SettingsSource.Header", "GitHub", "GitHub"),
    ("SettingsSpeed.Description", "Для всех треков", "For all tracks"),
    ("SettingsSpeed.Header", "Скорость воспроизведения", "Playback speed"),
    ("SettingsStorage.Text", "Хранилище", "Storage"),
    ("SettingsStorageDescription.Text", "Кэш освобождается сам: когда он заполнится, новые треки и обложки займут место тех, что дольше всех не слушали и не показывали. Делать ничего не нужно. Скачанное в кэш не входит и само не удаляется.", "Caches free themselves: once full, new tracks and artwork take the place of those unused the longest. There is nothing to do. Downloads are not part of the cache and are never removed on their own."),
    ("SettingsTheme.Header", "Тема", "Theme"),
    ("SettingsTitle.Text", "Настройки", "Settings"),
    ("SettingsVersion.Header", "Melogold", "Melogold"),
    ("SettingsWithoutAccount.Description", "Войдите, чтобы Избранное, плейлисты и сохранённое совпадали на всех устройствах", "Sign in to keep Favorites, playlists and saved items the same on all your devices"),
    ("SettingsWithoutAccount.Header", "Работает без аккаунта", "Works without an account"),
    ("ShareDelete", "Удалить ссылку", "Delete link"),
    ("ShareDeleteText", "Ссылка перестанет открываться у всех, кому вы её отправили. Сам плейлист останется.", "The link stops opening for everyone you sent it to. The playlist itself stays."),
    ("ShareDeleteTitleFormat", "Удалить ссылку на «{0}»?", "Delete the link to “{0}”?"),
    ("ShareDeleted", "Ссылка удалена", "Link deleted"),
    ("ShareFirstFifty", "Ссылка откроет первые 50 треков на YouTube", "The link opens the first 50 tracks on YouTube"),
    ("ShareGone", "Ссылка удалена или неверна", "The link was deleted or is wrong"),
    ("ShareLimitFormat", "Ссылок уже {0} — удалите старые в «Мои ссылки»", "You already have {0} links — delete old ones in “My links”"),
    ("ShareNoTracks", "В плейлисте нет треков YouTube — делиться нечем", "There are no YouTube tracks in this playlist to share"),
    ("ShareSaveToLibrary", "Сохранить в Библиотеку", "Save to Library"),
    ("ShareSavedToLibrary", "Сохранено в Библиотеку", "Saved to Library"),
    ("SharedPlaylist", "Плейлист по ссылке", "Shared playlist"),
    ("ShortcutBack", "Назад, закрыть «Сейчас играет»", "Back, close Now playing"),
    ("ShortcutClearSelection", "Снять выделение", "Clear selection"),
    ("ShortcutCursor", "Следующей отметить строку выше / ниже", "Mark the line above / below next"),
    ("ShortcutEditorSeek", "Назад / вперёд на 3 с", "Back / forward 3 s"),
    ("ShortcutFullScreen", "Во весь экран", "Full screen"),
    ("ShortcutHelp", "Сочетания клавиш", "Keyboard shortcuts"),
    ("ShortcutLike", "В Избранное или убрать из Избранного", "Add to or remove from Favorites"),
    ("ShortcutLyrics", "Текст песни", "Lyrics"),
    ("ShortcutMark", "Отметить строку или слово", "Mark the line or word"),
    ("ShortcutMarkEnd", "Конец строки", "End of line"),
    ("ShortcutMini", "Мини-плеер", "Mini player"),
    ("ShortcutMute", "Без звука или со звуком", "Mute or unmute"),
    ("ShortcutNextPrevious", "Следующий / предыдущий трек", "Next / previous track"),
    ("ShortcutNudge", "Последняя отметка раньше / позже на 0,1 с", "Last mark 0.1 s earlier / later"),
    ("ShortcutOr", "или", "or"),
    ("ShortcutPlayPause", "Играть или пауза", "Play or pause"),
    ("ShortcutQueue", "Очередь", "Queue"),
    ("ShortcutRemark", "Отметить последнюю строку заново", "Mark the last line again"),
    ("ShortcutRepeat", "Повтор: всё, один трек, выключен", "Repeat: all, one track, off"),
    ("ShortcutRowMenu", "Меню трека", "Track menu"),
    ("ShortcutRowMove", "Переместить выше / ниже в своём плейлисте", "Move up / down in your playlist"),
    ("ShortcutRowPlay", "Играть трек", "Play the track"),
    ("ShortcutRowRemove", "Убрать из плейлиста, истории или очереди", "Remove from the playlist, history or queue"),
    ("ShortcutSave", "Сохранить", "Save"),
    ("ShortcutSearch", "Поиск", "Search"),
    ("ShortcutSections", "Тренды / Новое / Библиотека", "Trends / New / Library"),
    ("ShortcutSeek", "Вперёд / назад на 5 с", "Forward / back 5 s"),
    ("ShortcutSelectAll", "Выделить все треки; несколько — Ctrl+щелчок и Shift+щелчок", "Select all tracks; several — Ctrl+click and Shift+click"),
    ("ShortcutSettings", "Настройки", "Settings"),
    ("ShortcutShuffle", "Перемешать", "Shuffle"),
    ("ShortcutUndo", "Отменить", "Undo"),
    ("ShortcutVolume", "Громче / тише", "Louder / quieter"),
    ("ShortcutsGroupEditor", "Редактор текста: синхронизация", "Lyrics editor: sync"),
    ("ShortcutsGroupLists", "Списки треков", "Track lists"),
    ("ShortcutsGroupPlayback", "Воспроизведение", "Playback"),
    ("ShortcutsGroupWindow", "Окно и разделы", "Window and sections"),
    ("ShortcutsTitle", "Сочетания клавиш", "Keyboard shortcuts"),
    ("Shuffle", "Перемешать", "Shuffle"),
    ("SignIn", "Войти", "Sign in"),
    ("SimilarAlbums", "Похожие альбомы", "Similar albums"),
    ("SimilarArtists", "Похожие исполнители", "Similar artists"),
    ("SizeGigabytesFormat", "{0} ГБ", "{0} GB"),
    ("SizeKilobytesFormat", "{0} КБ", "{0} KB"),
    ("SizeMegabytesFormat", "{0} МБ", "{0} MB"),
    ("SkippedFormat", "Пропущен „{0}“: {1}", "Skipped “{0}”: {1}"),
    ("SleepTimer", "Таймер сна", "Sleep timer"),
    ("SleepTimerEnded", "Таймер сна завершён", "Sleep timer ended"),
    ("SleepTimerLeftFormat", "Таймер сна · {0}", "Sleep timer · {0}"),
    ("SleepTimerOff", "Выключить таймер", "Turn off the timer"),
    ("SleepUntilTrackEnd", "До конца трека", "Until the end of the track"),
    ("SongCacheSizeBox.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Максимальный размер кэша песен", "Song cache max size"),
    ("Sort", "Сортировка", "Sort"),
    ("SortArtist", "Исполнитель", "Artist"),
    ("SortDuration", "Длительность", "Duration"),
    ("SortListeningTime", "Время прослушивания", "Listening time"),
    ("SortRecent", "Дата добавления", "Date added"),
    ("SortRecentlyPlayed", "Недавно слушали", "Recently played"),
    ("SortTitle", "Название", "Title"),
    ("SpeedNormal", "Обычная", "Normal"),
    ("Stats", "Итоги", "Insights"),
    ("StatsAlbums", "Альбомов", "Albums"),
    ("StatsAllTime", "Всё время", "All time"),
    ("StatsAllTimeNote", "Сервер хранит историю 400 дней: на новом устройстве видно столько, сколько пришло с сервера", "The server keeps the history for 400 days: on a new device you see as much as came from the server"),
    ("StatsArtists", "Исполнителей", "Artists"),
    ("StatsBusiestFormat", "Больше всего слушали: {0}, {1}", "Most listening: {0}, {1}"),
    ("StatsChangeFormat", "{0} % к {1}", "{0}% vs {1}"),
    ("StatsDayPartAfternoon", "День", "Afternoon"),
    ("StatsDayPartEvening", "Вечер", "Evening"),
    ("StatsDayPartMorning", "Утро", "Morning"),
    ("StatsDayPartNight", "Ночь", "Night"),
    ("StatsDiscovered_few", "{0} новых трека", "{0} new tracks"),
    ("StatsDiscovered_many", "{0} новых треков", "{0} new tracks"),
    ("StatsDiscovered_one", "{0} новый трек", "{0} new track"),
    ("StatsDiscovered_other", "{0} нового трека", "{0} new tracks"),
    ("StatsDiscoveries", "Открытия", "Discoveries"),
    ("StatsDiscoveriesText", "Услышаны впервые в этом периоде", "Heard for the first time in this period"),
    ("StatsEmpty", "За этот период прослушиваний нет", "No plays in this period"),
    ("StatsHint", "Неделя, месяц, год", "Week, month, year"),
    ("StatsHoursBusiestFormat", "Больше всего слушали около {0}, {1}", "Most listening around {0}, {1}"),
    ("StatsListeningTime", "Время прослушивания", "Listening time"),
    ("StatsMonth", "Месяц", "Month"),
    ("StatsMonthsCompare", "январю|февралю|марту|апрелю|маю|июню|июлю|августу|сентябрю|октябрю|ноябрю|декабрю", "January|February|March|April|May|June|July|August|September|October|November|December"),
    ("StatsNext", "Следующий период", "Next period"),
    ("StatsPictureFailed", "Не удалось сделать картинку", "Couldn't make the picture"),
    ("StatsPictureSaved", "Картинка сохранена", "Picture saved"),
    ("StatsPlays", "Прослушиваний", "Plays"),
    ("StatsPlaysCount_few", "{0} прослушивания", "{0} plays"),
    ("StatsPlaysCount_many", "{0} прослушиваний", "{0} plays"),
    ("StatsPlaysCount_one", "{0} прослушивание", "{0} play"),
    ("StatsPlaysCount_other", "{0} прослушивания", "{0} plays"),
    ("StatsPrevious", "Предыдущий период", "Previous period"),
    ("StatsRecap", "Итоги года", "Year in review"),
    ("StatsRecapDiscoveries", "Новое в этом году", "New this year"),
    ("StatsRecapEmpty", "За этот год пока нечего показать", "There is nothing to show for this year yet"),
    ("StatsRecapMinutes_few", "минуты музыки за год", "minutes of music this year"),
    ("StatsRecapMinutes_many", "минут музыки за год", "minutes of music this year"),
    ("StatsRecapMinutes_one", "минута музыки за год", "minute of music this year"),
    ("StatsRecapMinutes_other", "минуты музыки за год", "minutes of music this year"),
    ("StatsRecapMonth", "Любимый месяц", "Favorite month"),
    ("StatsRecapNewTracks_few", "новых трека", "new tracks"),
    ("StatsRecapNewTracks_many", "новых треков", "new tracks"),
    ("StatsRecapNewTracks_one", "новый трек", "new track"),
    ("StatsRecapNewTracks_other", "нового трека", "new tracks"),
    ("StatsRecapPageFormat", "Карточка {0} из {1}", "Card {0} of {1}"),
    ("StatsRecapPeakFormat", "Больше всего слушали около {0}", "Most listening around {0}"),
    ("StatsRecapReadyFormat", "Итоги {0} готовы", "Insights {0} are ready"),
    ("StatsRecapReadyText", "Посмотрите, что вы слушали в этом году", "See what you listened to this year"),
    ("StatsRecapTime", "Любимое время суток", "Favorite time of day"),
    ("StatsRecapTitleFormat", "Итоги {0}", "Insights {0}"),
    ("StatsRecapTrack", "Трек года", "Track of the year"),
    ("StatsSaveAs", "Сохранить как…", "Save as…"),
    ("StatsShare", "Поделиться", "Share"),
    ("StatsShareTextFormat", "Мой {0} год в Melogold", "My {0} in Melogold"),
    ("StatsShareWatermarkFormat", "Melogold · Итоги {0}", "Melogold · Insights {0}"),
    ("StatsShowAll", "Показать все", "Show all"),
    ("StatsShowLess", "Свернуть", "Show less"),
    ("StatsTimeOfDay", "Время суток", "Time of day"),
    ("StatsTopAlbums", "Лучшие альбомы", "Top albums"),
    ("StatsTopArtists", "Лучшие исполнители", "Top artists"),
    ("StatsTopTracks", "Лучшие треки", "Top tracks"),
    ("StatsTracks", "Треков", "Tracks"),
    ("StatsVsLastWeek", "прошлой неделе", "last week"),
    ("StatsVsMonthYearFormat", "{0} {1}", "{0} {1}"),
    ("StatsVsYearFormat", "{0} году", "{0}"),
    ("StatsWeek", "Неделя", "Week"),
    ("StatsWhen", "Когда вы слушали", "When you listened"),
    ("StatsYear", "Год", "Year"),
    ("StreamBitrate", "Битрейт", "Bitrate"),
    ("StreamInfoTitle", "Сведения о потоке", "Stream info"),
    ("StreamSource", "Клиент", "Client"),
    ("Subscribe", "Подписаться", "Subscribe"),
    ("Subscribed", "Вы подписаны", "Subscribed"),
    ("SyncStatusDoneFormat", "Синхронизировано · {0}", "Synced · {0}"),
    ("SyncStatusFailed", "Не удалось синхронизировать", "Couldn't sync"),
    ("SyncStatusNever", "Ещё не синхронизировано", "Not synced yet"),
    ("SyncStatusOffline", "Нет связи с сервером", "Can't reach the server"),
    ("SyncStatusSyncing", "Синхронизация…", "Syncing…"),
    ("ThemeDark.Content", "Тёмная", "Dark"),
    ("ThemeLight.Content", "Светлая", "Light"),
    ("ThemeSystem.Content", "Как в системе", "System default"),
    ("TrackDetailsAlbum", "Альбом", "Album"),
    ("TrackDetailsArtist", "Исполнитель", "Artist"),
    ("TrackDetailsName", "Название", "Title"),
    ("TrackDetailsReset", "Как на YouTube", "As on YouTube"),
    ("TrackDetailsSave", "Сохранить", "Save"),
    ("TrackDetailsTitle", "Сведения о треке", "Track details"),
    ("TrackHidden", "Трек скрыт", "Track hidden"),
    ("Tracks_few", "{0} трека", "{0} tracks"),
    ("Tracks_many", "{0} треков", "{0} tracks"),
    ("Tracks_one", "{0} трек", "{0} track"),
    ("Tracks_other", "{0} трека", "{0} tracks"),
    ("TrendsHeader", "Тренды", "Trends"),
    ("TrendsTitle.Text", "Тренды", "Trends"),
    ("TypeAlbum", "Альбом", "Album"),
    ("TypeArtist", "Исполнитель", "Artist"),
    ("TypeChannel", "Канал", "Channel"),
    ("TypePlaylist", "Плейлист", "Playlist"),
    ("TypeSong", "Песня", "Song"),
    ("TypeVideo", "Видео", "Video"),
    ("Undo", "Отменить", "Undo"),
    ("UpdateAction", "Обновить", "Update"),
    ("UpdateAvailableText", "{0} · установка займёт минуту, всё останется на месте", "{0} · takes a minute, everything stays in place"),
    ("UpdateAvailableTitle", "Вышла новая версия {0}", "Version {0} is out"),
    ("UpdateChecking", "Проверка…", "Checking…"),
    ("UpdateDisabledFormat", "Версия {0} · эта сборка не обновляется сама", "Version {0} · this build doesn't update itself"),
    ("UpdateDownloadingFormat", "Скачивание обновления · {0} %", "Downloading the update · {0}%"),
    ("UpdateFailed", "Не удалось скачать обновление. Попробуйте ещё раз", "Couldn't download the update. Try again"),
    ("UpdateInstalling", "Установка…", "Installing…"),
    ("UpdateLater", "Позже", "Later"),
    ("UpdateOfflineFormat", "Версия {0} · нет связи с GitHub", "Version {0} · can't reach GitHub"),
    ("UpdateToastText", "Нажмите, чтобы посмотреть, что нового, и обновить", "Click to see what’s new and update"),
    ("UpdateUpToDateFormat", "Версия {0} · последняя", "Version {0} · up to date"),
    ("UpdateVersionNewFormat", "Версия {0} · вышла {1}", "Version {0} · {1} is out"),
    ("UpdateWhatsNew", "Что нового", "What's new"),
    ("UpdateWhatsNewTitle", "Что нового в {0}", "What's new in {0}"),
    ("VersionFormat", "Версия {0}", "Version {0}"),
    ("Year", "Год", "Year"),
    ("YouTubeChannel", "Канал YouTube", "YouTube channel"),
];
